export const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vehicula suscipit mollis. Quisque suscipit nisi tellus, ut hendrerit dolor lacinia ac. Nulla facilisi. Nullam ac ipsum facilisis, condimentum sem ut, bibendum sapien. Nam eu ante nisl. Nunc id felis ornare, pharetra ipsum vel, luctus turpis. Fusce nisl odio, gravida a malesuada convallis, consequat ut sapien. Cras justo quam, dignissim nec porttitor eu, convallis vitae neque. Proin vel velit quis turpis convallis sagittis dignissim at erat. Pellentesque volutpat a lorem et iaculis.

Cras vitae lacinia nulla. Ut ac bibendum purus, id rutrum erat. Etiam eget mi non augue placerat vestibulum non ut augue. Cras pharetra sagittis pulvinar. Sed convallis at est eu cursus. Proin et luctus augue. Integer ut lectus sagittis, tristique massa vitae, luctus lorem. Cras fermentum nunc libero, in suscipit sem auctor eget. Morbi vitae magna vitae felis tincidunt iaculis non eu elit. Sed cursus sed erat a accumsan. Nunc molestie a turpis laoreet accumsan. Sed a erat facilisis, imperdiet nulla et, posuere lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Etiam luctus sapien at quam tincidunt gravida. Sed viverra lorem id maximus molestie. Sed leo diam, molestie et eros vel, feugiat placerat magna. In id dui blandit, finibus turpis porta, ultricies metus. Aenean gravida feugiat gravida. Cras in urna erat. Donec dignissim dapibus ultricies. Nulla mi tortor, mollis quis ullamcorper ac, molestie id massa.

Nullam sem mi, consequat vitae tellus sit amet, commodo hendrerit lorem. Sed interdum risus faucibus, tristique sem id, fermentum risus. Donec non mi sed nisi vehicula ultricies. Cras hendrerit nisl ac augue volutpat, at accumsan ante pretium. Nam aliquam neque purus. Donec eu mauris in mi sollicitudin bibendum id ac enim. Etiam diam nulla, porttitor sit amet dictum eget, mollis in odio. Duis vestibulum eget lectus sodales consectetur. Donec ut posuere libero. Vestibulum placerat lorem augue, ut bibendum lorem tincidunt a. Cras aliquam dolor et aliquam mattis. Proin porttitor placerat orci ac sodales. Donec commodo sit amet sem in ornare. Nunc luctus ipsum mi, vitae tempus justo efficitur sed. Fusce a tortor non felis congue mattis.

Curabitur ultrices magna in sollicitudin feugiat. Nam mattis pellentesque mauris, at posuere lacus pulvinar vitae. Aliquam fermentum mauris et dictum pretium. Sed viverra dignissim metus eu pellentesque. Donec aliquam felis a arcu sollicitudin vulputate. Nullam vel venenatis sapien. Curabitur mattis dolor in orci tristique cursus. Proin porta mauris at mi finibus posuere. Sed blandit, libero eu efficitur rutrum, turpis est consectetur neque, in lacinia massa magna non dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque vehicula maximus suscipit. Fusce neque tellus, vestibulum ac tellus et, cursus placerat eros. Mauris ac nulla aliquet, semper nulla vel, lacinia sem. Aenean ornare varius nulla, id bibendum purus.

Morbi a facilisis mauris, in dignissim urna. Quisque auctor purus id elit consequat, quis pellentesque ligula scelerisque. Morbi vitae quam vitae ante varius porttitor at ullamcorper magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus quis odio varius, fringilla sapien nec, sagittis metus. Aenean volutpat quam et posuere dictum. Suspendisse eleifend, magna auctor suscipit auctor, augue elit iaculis neque, non elementum ante odio quis nisl.

Praesent facilisis odio metus, nec blandit felis feugiat tincidunt. Suspendisse venenatis nisi vitae tortor mollis porta. Morbi pharetra quam erat, et sodales lectus scelerisque in. Pellentesque eu tortor venenatis, pharetra mi sed, feugiat quam. Sed consectetur odio accumsan erat feugiat convallis. In mollis, neque sit amet pharetra vestibulum, tortor nibh tristique risus, sit amet sodales diam magna id ipsum. Duis posuere gravida sem, id accumsan elit tristique commodo. Duis vulputate ex id erat semper, id condimentum tellus posuere.

Nam metus justo, tempus porttitor euismod at, sollicitudin ac orci. Nam molestie posuere pellentesque. Pellentesque ullamcorper accumsan lectus venenatis vehicula. Ut non pretium sem. Sed consectetur, urna nec laoreet facilisis, metus ex consectetur erat, in consectetur tellus eros eu lectus. Mauris euismod leo a diam faucibus scelerisque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris euismod nunc vel magna ullamcorper porttitor. Sed aliquam leo ut mi efficitur mattis. Nulla vulputate augue sed libero sagittis luctus. Maecenas ut mi eget mi vestibulum fringilla non sed nulla. Sed cursus quam et sapien egestas, ac dapibus metus lacinia. Integer vestibulum turpis libero, sit amet finibus neque mollis non.`
